Controllers/HairdresserController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using maturitetna.Models;
using maturitetna.Data;
using maturitetna.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace maturitetna.Controllers;
[ServiceFilter(typeof(SessionCheckFilterHairdresser))]
public class HairdresserController : Controller
{
    private readonly ILogger<AdminController> _logger;
    private readonly ApplicationDbContext _db;

    public HairdresserController(ILogger<AdminController> logger, ApplicationDbContext db)
    {
        _db = db;
        _logger = logger;
    }

    public IActionResult Index()
    {
        var my_appointments = _db.appointment.Where(a => a.id_hairdresser == int.Parse(HttpContext.Session.GetString("id")) && a.appointmentTime >= DateTime.Now).Include(a => a.user).Include(a => a.haircut);

        var currentDay = DateTime.Today;
        var startOfWeek = currentDay.AddDays(-1 * (int)currentDay.DayOfWeek);
        var endOfWeek = startOfWeek.AddDays(6);

        int appointmentsToday = my_appointments.Where(a => a.appointmentTime.Date == DateTime.Today).Count();
        int appointmentsThisWeek = my_appointments.Where(a => a.appointmentTime.Date >= startOfWeek && a.appointmentTime.Date <= endOfWeek).Count();
        int appointmentsThisMonth = my_appointments.Where(a => a.appointmentTime.Month == currentDay.Month).Count();

        var stats = new
        {
            appointments_today = appointmentsToday,
            appointments_this_week = appointmentsThisWeek,
            appointments_this_month = appointmentsThisMonth,
        };

        return View(new { my_appointments = my_appointments.OrderBy(a => a.appointmentTime), stats = stats });
    }


    public IActionResult Profile()
    {
        if (HttpContext.Session.GetString("id") != null)
        {
            int i = int.Parse(HttpContext.Session.GetString("id"));
            var hairdresser = _db.hairdresser.Find(i);
           

            ViewBag.File = FileHelper.GetProfilePicture(i, 'h');

            return View(hairdresser);
        }
        else return RedirectToAction("Index", "Home");
    }
    
    [HttpPost]
    public IActionResult Profile(hairdresserEntity hairdresser, IFormFile fileName)
    {
        hairdresser.id_hairdresser = int.Parse(HttpContext.Session.GetString("id"));
        Console.WriteLine( hairdresser.id_hairdresser + " " +  hairdresser.name + " " +  hairdresser.lastname + " "  + 'h');
        var user = _db. hairdresser.Find( hairdresser.id_hairdresser);
        user.name =  hairdresser.name;
        user.lastname =  hairdresser.lastname;
        user.email =  hairdresser.email;

        user.startTime = hairdresser.startTime;
        user.endTime = hairdresser.endTime;
        user.is_working = hairdresser.is_working;

        // if( hairdresser.password != null) user.password = PasswordHelper.HashPassword( hairdresser.password);
        _db.SaveChanges();
    
        if (fileName != null)
        {
            // Sanitize the file name to remove invalid characters
            string sanitizedFileName = string.Join("_",  hairdresser.id_hairdresser.ToString(), 'h') + ".png";
            sanitizedFileName = new string(sanitizedFileName.Where(c => !Path.GetInvalidFileNameChars().Contains(c)).ToArray());

// Combine the sanitized file name with the path
            string filePath = Path.Combine("wwwroot/Storage/ProfilePics", sanitizedFileName);

// Use the sanitized file path in FileStream
            using (var stream = new FileStream(filePath, FileMode.Create))
            {
                fileName.CopyTo(stream);
            }

            
            
            // using (var stream = new FileStream("wwwroot/Storage/ProfilePics/" + admin.rights.ToString() + admin.id_admin.ToString() + ".png", FileMode.Create))
            // {
            //     fileName.CopyTo(stream);
            // }
        }
        ViewBag.File = FileHelper.GetProfilePicture( hairdresser.id_hairdresser, 'h');
        return View(user);
    }

    public async Task<IActionResult> ToggleMyHaircut(int id_haircut)
    {
        if (await _db.hairdresserHaircut.FirstOrDefaultAsync(hh => hh.id_haircut == id_haircut && hh.id_hairdresser == int.Parse(HttpContext.Session.GetString("id"))) == null)
        {
            var hh = new hairdresserHaircutEntity
            {
                id_haircut = id_haircut,
                id_hairdresser = int.Parse(HttpContext.Session.GetString("id"))
            };
            await _db.hairdresserHaircut.AddAsync(hh);
            await _db.SaveChangesAsync();
        }
        else
        {
            var hh = await _db.hairdresserHaircut.FirstOrDefaultAsync(hh => hh.id_haircut == id_haircut && hh.id_hairdresser == int.Parse(HttpContext.Session.GetString("id")));
            _db.hairdresserHaircut.Remove(hh);
            await _db.SaveChangesAsync();
        }

        return RedirectToAction("MyHaircuts");
    }

    [HttpPost]
    public IActionResult CancelAppointment(int appointment_id)
    {
        var hairdresser_id = int.Parse(HttpContext.Session.GetString("id"));
        var appointment = _db.appointment.Find(appointment_id);
        if (appointment == null || appointment.id_hairdresser != hairdresser_id)
        {
            return RedirectToAction("Index");
        }
        _db.appointment.Remove(appointment);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

    public async Task<IActionResult> MyHaircuts()
    {
        var allHaircuts = await _db.haircut.ToListAsync();

        var myHaircuts = await _db.hairdresserHaircut.Where(hh => hh.id_hairdresser == int.Parse(HttpContext.Session.GetString("id"))).ToListAsync();

        return View(new {
            myHaircuts,
            allHaircuts
        });
    }

    public IActionResult DaysOff()
    {
        return View();
    }
    
    public IActionResult Logout()
    {
        HttpContext.Session.Clear(); // Clear all session data
        return RedirectToAction("Index", "Home");
    }
}
    

Controllers/UserController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using maturitetna.Models;
using maturitetna.Data;
using maturitetna.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace maturitetna.Controllers;
[ServiceFilter(typeof(SessionCheckFilterUser))]
public class UserController : Controller
{
    private readonly ILogger<AdminController> _logger;
    private readonly ApplicationDbContext _db;

    public UserController(ILogger<AdminController> logger, ApplicationDbContext db)
    {
        _db = db;
        _logger = logger;
    }

    public IActionResult Index()
    {
        var my_appointments = _db.appointment.Where(a => a.id_user == int.Parse(HttpContext.Session.GetString("id")) && a.appointmentTime >= DateTime.Now && a.reschedulingId == 0).Include(a => a.hairdresser).Include(a => a.haircut).OrderBy(a => a.appointmentTime);

        var my_recurring_appointments_query = _db.appointment.Where(a => a.id_user == int.Parse(HttpContext.Session.GetString("id")) && a.appointmentTime >= DateTime.Now && a.reschedulingId != 0)
            .OrderBy(a => a.appointmentTime)
            .Include(a => a.hairdresser)
            .Include(a => a.haircut);

        var appointments_to_update = my_recurring_appointments_query.Where(a => a.rescheduleIn14Days == true && a.appointmentTime < DateTime.Now.AddDays(7)).ToList();

        foreach (var appointment in appointments_to_update)
        {
            _db.appointment.Add(new appointmentEntity
            {
                id_user = appointment.id_user,
                id_hairdresser = appointment.id_hairdresser,
                id_haircut = appointment.id_haircut,
                appointmentTime = appointment.appointmentTime.AddDays(14),
                created = DateTime.UtcNow,
                reschedulingId = appointment.reschedulingId,
                rescheduleIn14Days = true,
            });

            appointment.rescheduleIn14Days = false;
        }

        _db.SaveChanges();


        var my_recurring_appointments = my_recurring_appointments_query
            .AsEnumerable()
            .DistinctBy(a => a.reschedulingId).ToList();

        if (my_appointments.Count() == 0 && my_recurring_appointments.Count() == 0) return View(null);
        return View(new { my_appointments, my_recurring_appointments });
    }


      public IActionResult Profile()
    {
        if (HttpContext.Session.GetString("id") != null)
        {
            int i = int.Parse(HttpContext.Session.GetString("id"));
            var user = _db.user.Find(i);
           

            ViewBag.File = FileHelper.GetProfilePicture(i, 'u');

            return View(user);

        }
        else return RedirectToAction("Index", "Home");

            
    }
    
    [HttpPost]
    public IActionResult Profile(userEntity user, IFormFile fileName)
    {
        user.id_user = int.Parse(HttpContext.Session.GetString("id"));
        Console.WriteLine(user.id_user + " " + user.name + " " + user.lastname + " "  + 'u');
        var variable = _db.user.Find(user.id_user);
        variable.name = user.name;
        variable.lastname = user.lastname;
        variable.email = user.email;
        if(user.password != null) variable.password = PasswordHelper.HashPassword(user.password);
        _db.SaveChanges();
    
        if (fileName != null)
        {
            // Sanitize the file name to remove invalid characters
            string sanitizedFileName = string.Join("_", user.id_user.ToString(), 'u') + ".png";
            sanitizedFileName = new string(sanitizedFileName.Where(c => !Path.GetInvalidFileNameChars().Contains(c)).ToArray());

// Combine the sanitized file name with the path
            string filePath = Path.Combine("wwwroot/Storage/ProfilePics", sanitizedFileName);

// Use the sanitized file path in FileStream
            using (var stream = new FileStream(filePath, FileMode.Create))
            {
                fileName.CopyTo(stream);
            }

            
            
            // using (var stream = new FileStream("wwwroot/Storage/ProfilePics/" + admin.rights.ToString() + admin.id_admin.ToString() + ".png", FileMode.Create))
            // {
            //     fileName.CopyTo(stream);
            // }
        }
        ViewBag.File = FileHelper.GetProfilePicture(user.id_user, 'u');
        return View(variable);
    }



    public IActionResult Logout()
    {
        HttpContext.Session.Clear(); // Clear all session data
        return RedirectToAction("Index", "Home");
    }
    

    public IActionResult Style()
    {
        var haircuts = _db.haircut.ToList();

        return View(haircuts);
    }

    public IActionResult Calendar(int id_haircut)
    {
        var haircut = _db.haircut.Find(id_haircut);


        return View(haircut);
    }

    // Helper method to check if a given datetime is within working hours
    private bool IsWithinWorkingHours(DateTime appointmentTime, TimeSpan workingStartTime, TimeSpan workingEndTime)
    {
        if (DateTime.UtcNow.AddDays(14) < appointmentTime) return false;

        TimeSpan appointmentStartTime = appointmentTime.TimeOfDay;

        return appointmentStartTime >= workingStartTime && appointmentStartTime <= workingEndTime;
    }

    // Helper method to check if there are overlapping appointments for the chosen hairdresser at the specified date and time
    private bool IsAppointmentOverlap(int hairdresserId, DateTime appointmentTime, int haircutDuration)
    {
        var overlappingAppointments = _db.appointment
            .Where(a => a.id_hairdresser == hairdresserId && a.appointmentTime < appointmentTime.AddMinutes(haircutDuration) && a.appointmentTime.AddMinutes(a.haircut.duration) > appointmentTime)
            .Any();

        return overlappingAppointments;
    }

    public IActionResult MakeAppointment(int id_hairdresser, int id_haircut, int day, int month, int year, TimeSpan time, bool rescheduleIn2Weeks)
    {
        var hairdresser = _db.hairdresser.Find(id_hairdresser);
        if (hairdresser == null)
        {
            // Hairdresser does not exist
            return RedirectToAction("Calendar", new { id_haircut = id_haircut });
        }
        if (hairdresser.is_working == false)
        {
            // Hairdresser is not working
            return RedirectToAction("Calendar", new { id_haircut = id_haircut });
        }

        var haircut = _db.haircut.Find(id_haircut);
        if (haircut == null)
        {
            // Haircut does not exist
            return RedirectToAction("Calendar", new { id_haircut = id_haircut });
        }

        var hairdresser_haircut = _db.hairdresserHaircut.Any(hh => hh.id_haircut == id_haircut && hh.id_hairdresser == id_hairdresser);
        if (!hairdresser_haircut)
        {
            // Hairdresser does not offer this haircut
            return RedirectToAction("Calendar", new { id_haircut = id_haircut });
        }

        var haircutDuration = haircut.duration;
        
        var appointmentTime = new DateTime(year, month, day, time.Hours, time.Minutes, 0);

        // Check if the selected date and time are within the working hours of the hairdresser
        if (!IsWithinWorkingHours(appointmentTime, hairdresser.startTime, hairdresser.endTime))
        {
            // Selected time is outside working hours
            return RedirectToAction("Calendar", new { id_haircut = id_haircut });
        }

        // Check if there are overlapping appointments for the chosen hairdresser at the specified date and time
        if (IsAppointmentOverlap(id_hairdresser, appointmentTime, haircutDuration))
        {
            // Overlapping appointment
            return RedirectToAction("Calendar", new { id_haircut = id_haircut });
        }

        var user = _db.user.Find(int.Parse(HttpContext.Session.GetString("id")));

        // All checks passed, create a new appointment
        var newAppointment = new appointmentEntity
        {
            id_user = user.id_user,
            id_hairdresser = id_hairdresser,
            id_haircut = id_haircut,
            appointmentTime = appointmentTime,
            created = DateTime.UtcNow,
            rescheduleIn14Days = false,
            reschedulingId = rescheduleIn2Weeks ? appointmentTime.Ticks.GetHashCode() : 0
        };

        // Save the new appointment to the database
        _db.appointment.Add(newAppointment);

        if (rescheduleIn2Weeks) {
            _db.appointment.Add(new appointmentEntity
            {
                id_user = user.id_user,
                id_hairdresser = id_hairdresser,
                id_haircut = id_haircut,
                appointmentTime = appointmentTime.AddDays(14),
                created = DateTime.UtcNow,
                reschedulingId = newAppointment.reschedulingId,
                rescheduleIn14Days = true,
            });
        }

        _db.SaveChanges();

        MailService.SendConfirmAppointment(newAppointment);

        return View(newAppointment);
    }

    public IActionResult AvailableOnDay(int id_haircut, int year, int month, int day)
    {
        var haircut = _db.haircut.Find(id_haircut);
        if (haircut == null)
        {
            // Haircut does not exist
            return RedirectToAction("Calendar", new { id_haircut = id_haircut });
        }

        var selectedDate = new DateTime(year, month, day);
        var currentDate = DateTime.Now;

        if (selectedDate < currentDate.Date || selectedDate > currentDate.AddDays(14))
        {
            // Selected date is in the past or more than 14 days in the future
            return RedirectToAction("Calendar", new { id_haircut = id_haircut });
        }
        var hairdressersIds = _db.hairdresserHaircut.Where(hh => hh.id_haircut == id_haircut).Select(hh => hh.id_hairdresser).ToList();

        var hairdressers = _db.hairdresser.Where(h => hairdressersIds.Contains(h.id_hairdresser) && h.is_working).ToList();

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - maturitetna</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/maturitetna.styles.css" asp-append-version="true" />
</head>
<body>
   
    <div class="containerIndex">
        <main role="main" class="pb-3">
            
          
            
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="">
           
            &copy; 2023 - maturitetna - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - maturitetna</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Admin.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 center">
            <div class="container-fluid">
                <a class="navbar-brand background-dark rounded-3" asp-area="" asp-controller="Admin" asp-action="Index"><img class="icon" src="~/Storage/ProfilePics/1.jpeg"/> </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item expand">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Profile">Profile</a>
                        </li>
                        <li class="nav-item expand">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Index</a>
                            </li>
                        <li class="nav-item expand">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Users">Users</a>
                        </li>
                        <li class="nav-item expand">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Admins">Admins</a>
                        </li>
                        <li class="nav-item expand">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Hairdressers">Hairdressers</a>
                        </li>
                         <li class="nav-item expand float-right">
                             <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Logout">Logout</a>
                          </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="containerAdmin">
        <main role="main" class="pb-3">
            
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="">
            &copy; 2023 - maturitetna - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LayoutHairdresser.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - maturitetna</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Hairdresser.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 center">
            <div class="container-fluid">
                <a class="navbar-brand background-dark rounded-3" asp-area="" asp-controller="Hairdresser" asp-action="Index"><img class="icon" src="~/Storage/ProfilePics/1.jpeg"/> </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item expand">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Hairdresser" asp-action="Profile">Profile</a>
                        </li>
                        <li class="nav-item expand">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Hairdresser" asp-action="MyHaircuts">MyHaircuts</a>
                        </li>
                        <li class="nav-item expand">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Hairdresser" asp-action="Index">Index</a>
                            </li>
                      
                         <li class="nav-item expand float-right">
                             <a class="nav-link text-dark" asp-area="" asp-controller="Hairdresser" asp-action="Logout">Logout</a>
                          </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="containerAdmin">
        <main role="main" class="pb-3">
            
          
            
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="">
            &copy; 2023 - maturitetna - <a asp-area="" asp-controller="" asp-action="">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/Hairdresser.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LayoutUser.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - maturitetna</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/user.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 center">
            <div class="container-fluid">
                <a class="navbar-brand background-dark rounded-3" asp-area="" asp-controller="User" asp-action="Index"><img class="icon" src="~/Storage/ProfilePics/1.jpeg"/> </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item expand">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Profile">Profile</a>
                        </li>
                        <li class="nav-item expand">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Index</a>
                            </li>
                      
                         <li class="nav-item expand float-right">
                             <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Logout">Logout</a>
                          </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="containerAdmin">
        <main role="main" class="pb-3">
            
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="">
            &copy; 2023 - maturitetna - <a asp-area="" asp-controller="" asp-action="">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>